spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 15242635
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1

logging:
  level:
    root: info
jwt:
  expiration: 2592000
